# Generated by Django 4.0.1 on 2022-01-13 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('rooms', models.IntegerField()),
                ('size', models.FloatField()),
                ('street', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('S', 'Sale'), ('R', 'Rent')], max_length=1)),
                ('immovable_type', models.CharField(choices=[('A', 'Apartment'), ('H', 'House')], max_length=1)),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DayVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('timetables', models.TimeField()),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('F', 'Finalized'), ('C', 'Canceled')], default='S', max_length=1)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.building')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.city'),
        ),
        migrations.AddField(
            model_name='building',
            name='images',
            field=models.ManyToManyField(to='home.Image'),
        ),
        migrations.AddField(
            model_name='building',
            name='timetables',
            field=models.ManyToManyField(to='home.Timetable'),
        ),
        migrations.AddField(
            model_name='building',
            name='visit_days',
            field=models.ManyToManyField(to='home.DayVisit'),
        ),
    ]
