# Generated by Django 4.0.1 on 2022-01-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_visits_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayvisit',
            name='day',
            field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wendnesdat'), ('Th', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('Su', 'Sunday')], max_length=20),
        ),
    ]
