# Generated by Django 4.0.1 on 2022-01-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_dayvisit_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visits',
            old_name='timetables',
            new_name='timetable',
        ),
    ]
